version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-

      - run:
          command: | 
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            R -e 'install.packages("tinytex", dependencies = TRUE)'
      - run:
          command: |
            R -e 'source("tests/tests.R")'

          ## store artifacts -----------------
      - store_test_results:
          path: /tmp/Rcheck/tests/
          when: always
      - store_artifacts:
          path: /tmp/Rcheck
          when: always