<<echo=FALSE, results=hide>>=
## Exercício 1 (slides MCU): período do ponteiro dos segundos

resp1 <- 60        ## período, em s
resp2 <- 1/60      ## frequência, em Hz
resp3 <- 1/60*60   ## frequência, em rpm
@

\begin{question}

(Adaptado de slides de apoio) Em um relógio analógico, o ponteiro dos segundos completa uma volta a cada $60$ segundos.

\begin{answerlist}
  \item O período do ponteiro dos segundos, em segundos.
  \item A frequência do ponteiro dos segundos, em hertz. \textit{Dê sua resposta na forma de fração (ex.: 1/60) ou com 4 casas decimais.}
  \item A frequência do ponteiro dos segundos, em rotações por minuto (rpm).
\end{answerlist}
\end{question}

\begin{solution}

\begin{answerlist}
  \item T = $\Sexpr{resp1}$ s
  \item f = $\Sexpr{resp2}$ Hz
  \item f = $\Sexpr{resp3}$ rpm
\end{answerlist}
\end{solution}

%% META-INFORMATION
%% \extype{cloze}
%% \exsolution{\Sexpr{resp1}|\Sexpr{resp2}|\Sexpr{resp3}}
%% \exclozetype{num|num|num}
%% \exname{Q04PonteiroSegundos}
%% \extol{0.1|0.0001|0.1}
