<<echo=FALSE, results=hide>>=
## Marcelo C.
m <- sample(seq(from=60,to=90,by=1),1)
b <- sample(seq(from=2.0,to=4.0,by=1),1)
respa <- b*m
respb <- (m+respa)*10
@

\begin{question}

(UNICAMP) Um homem de \Sexpr{m} kg, quer levantar um objeto usando uma alavanca rígida e leve. Os braços da alavanca têm 1 e \Sexpr{b} m. Considerando a aceleração da gravidade $g = 10m/s^2$, responda:

\begin{answerlist}
  \item Qual a maior massa, em quilogramas, que o homem consegue levantar usando a alavanca e seu próprio peso?
  \item Neste caso, qual a força, em Newtons, exercida sobre a alavanca no ponto de apoio?
\end{answerlist}
\end{question}

\begin{solution}
Seja \(M\) a maior massa que pode ser levantada. No limite de equilíbrio, o peso do homem atua no braço de comprimento \(\Sexpr{b}\,\mathrm{m}\) e o peso do objeto no braço de \(1\,\mathrm{m}\). Pelo equilíbrio dos torques,
\[
  (mg)\,\Sexpr{b}=(Mg)\,1,
\]
de modo que
\[
  M=\Sexpr{b}\,m=\Sexpr{respa}\,\mathrm{kg}.
\]

A força no ponto de apoio deve equilibrar verticalmente os dois pesos. Portanto,
\[
  R=(m+M)g
   =(\Sexpr{m}+\Sexpr{respa})\,10
   =\Sexpr{respb}\,\mathrm{N}.
\]

\begin{answerlist}
  \item \Sexpr{respa} kg
  \item \Sexpr{respb} N
\end{answerlist}

\end{solution}

%% META-INFORMATION
%% \extype{cloze}
%% \exsolution{\Sexpr{respa}|\Sexpr{respb}}
%% \exclozetype{num|num}
%% \exname{Q03estce}
%% \extol{0.1|0.1}