<<echo=FALSE, results=hide>>=
#Marcelo C.
include_supplement("Q04estce.jpg")

peso <- sample(seq(from=30000,to=60000,by=500),1)
resp <- 1.5*peso
@
\usepackage{graphicx}
\usepackage[portuguese]{babel}


\begin{question}

(FUVEST 2015 adapt.) O guindaste da figura acima pesa \Sexpr{peso} N sem carga e os pontos de apoio de suas rodas no solo horizontal estão em x = 0 e x = –5m. O centro de massa (CM) do guindaste sem carga está localizado na posição (x = – 3m, y = 2m). Na situação mostrada na figura, determine a maior carga P, em Newtons, que esse guindaste pode levantar.

\includegraphics[height=6cm,keepaspectratio]{Q04estce.jpg}
\end{question}


\begin{solution}
A maior carga ocorre no limite de tombamento, quando a reação do apoio traseiro se anula e o guindaste fica prestes a girar em torno do apoio em \(x=0\).

O peso do guindaste atua em \(x=-3\,\mathrm{m}\), portanto seu braço de alavanca é \(3\,\mathrm{m}\). A carga \(P\) atua em \(x=2\,\mathrm{m}\), com braço de \(2\,\mathrm{m}\). No limite,
\[
  \Sexpr{peso}\cdot 3=P\cdot 2.
\]
Assim,
\[
  P=\frac{3}{2}\,\Sexpr{peso}
   =\Sexpr{resp}\,\mathrm{N}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q04estce}
%% \extol{1}