<<echo=FALSE, results=hide>>=
## DATA GENERATION EXAMPLE

m1 <- sample(seq(from=20,to=26,by=0.5),1)
m2 <- sample(seq(from=54,to=60,by=0.5),1)
resp <- (m2-m1*2)*2
include_supplement("Q10estce.jpg")

@
\usepackage[portuguese]{babel}
\usepackage{graphicx}

\begin{question}

(UFPE) Uma tábua uniforme de $3 m$ de comprimento é usada como gangorra por duas crianças com massas $\Sexpr{m1} kg$ e $\Sexpr{m2} kg$. Elas sentam sobre as extremidades da tábua de modo que o sistema fica em equilíbrio quando apoiado em uma pedra distante $1,0 m$ da criança mais pesada. Qual a massa, em $kg$, da tábua?

\includegraphics[height=6cm,keepaspectratio]{Q10estce.jpg}

\end{question}

\begin{solution}
A criança mais pesada está a \(1{,}0\,\mathrm{m}\) do apoio. Como a tábua mede \(3\,\mathrm{m}\), a criança mais leve está a \(2{,}0\,\mathrm{m}\) do apoio.

O centro de massa da tábua está no seu ponto médio, a \(1{,}5\,\mathrm{m}\) da extremidade onde está a criança mais pesada. Portanto, ele fica a \(0{,}5\,\mathrm{m}\) do apoio, do lado da criança mais leve.

Se \(M\) é a massa da tábua, o equilíbrio dos torques fornece
\[
  \Sexpr{m2}g\cdot1
  =\Sexpr{m1}g\cdot2+Mg\cdot0{,}5.
\]
Cancelando \(g\),
\[
  M=2\left(\Sexpr{m2}-2\Sexpr{m1}\right)
   =\Sexpr{resp}\,\mathrm{kg}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q10estce}
%% \extol{0.01}