<<echo=FALSE, results=hide>>=
## Marcelo C.

Flim <- sample(seq(from=25,to=100,by=1),1)
l <- sample(seq(from=20,to=80,by=1),1)
P <- sample(seq(from=10,to=1.5*Flim,by=1),1)
resp = round(l*P/(2*Flim),2)

include_supplement("Q15estce.jpg")

@
\usepackage[portuguese]{babel}
\usepackage{graphicx}

\begin{question}

(Cesgranrio-adapt.) Um fio, cujo limite de resistência é de $\Sexpr{Flim} N$, é utilizado para manter em equilíbrio, na posição horizontal, uma haste de metal, homogênea, de comprimento $AB = \Sexpr{l} cm$ e $peso = \Sexpr{P} N$.
A barra é fixa em A, numa parede, através de uma articulação, conforme indica a figura a seguir. Determine a menor distância $x$, em $cm$, para a qual o fio manterá a haste em equilíbrio. Caso necessário, arredonde sua resposta para 1 casa decimal.

\includegraphics[height=6cm,keepaspectratio]{Q15estce.jpg}

\end{question}

\begin{solution}
O menor valor de \(x\) ocorre quando o fio trabalha exatamente no seu limite de resistência,
\[
  T=F_{\mathrm{lim}}=\Sexpr{Flim}\,\mathrm{N}.
\]

Tomando os torques em relação à articulação \(A\), a tração atua a uma distância \(x\), enquanto o peso da haste homogênea atua em seu centro, a \(l/2\):
\[
  T\,x=P\frac{l}{2}.
\]

Assim,
\[
  x=\frac{Pl}{2T}
   =\frac{\Sexpr{P}\cdot\Sexpr{l}}
          {2\cdot\Sexpr{Flim}}
   =\Sexpr{resp}\,\mathrm{cm}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q15estce}
%% \extol{0.1}