<<echo=FALSE, results=hide>>=
## Marcelo C.

m <- sample(seq(from=1,to=300,by=1),1)
resp = round(m*10*sqrt(3)/2,2)

include_supplement("Q16estpm.jpg")

@
\usepackage[portuguese]{babel}
\usepackage{graphicx}

\begin{question}

(UNIRIO-adapt.) Uma caixa de massa $m = \Sexpr{m}$ kg está em equilíbrio estático conforme mostra a figura.

\includegraphics[height=6cm,keepaspectratio]{Q16estpm.jpg}

Considerando os fios ideais e de pesos desprezíveis, determine a tração na corda BC, em N. Dados: $g = 10m/s^2$ ; $sen30^{\circ}=0,5$ e $cos30^{\circ}=0,866$. Caso necessário, arredonde sua resposta para 1 casa decimal.

\end{question}

\begin{solution}
No nó \(B\) atuam três forças: o peso \(mg\), a tração \(T_{AB}\) e a tração \(T_{BC}\).

No eixo horizontal,
\[
  T_{AB}\cos30^\circ=T_{BC}\cos60^\circ.
\]
Como \(\cos30^\circ=\sqrt{3}/2\) e \(\cos60^\circ=1/2\),
\[
  T_{BC}=\sqrt{3}\,T_{AB}.
\]

No eixo vertical,
\[
  T_{AB}\sin30^\circ+T_{BC}\sin60^\circ=mg.
\]
Substituindo \(T_{BC}=\sqrt{3}T_{AB}\),
\[
  \frac{1}{2}T_{AB}
  +\frac{\sqrt{3}}{2}\left(\sqrt{3}T_{AB}\right)
  =2T_{AB}=mg.
\]
Portanto,
\[
  T_{BC}=\frac{\sqrt{3}}{2}mg
        =\frac{\sqrt{3}}{2}\,\Sexpr{m}\cdot10
        =\Sexpr{resp}\,\mathrm{N}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q16estpm}
%% \extol{0.1}