<<echo=FALSE, results=hide>>=
## DATA GENERATION 
R = sample(100:150,1)
v = sample(30:50,1)
m = sample(1200:1600,1)

## Resposta
forca = round(m*sqrt((v^4)/(R^2) + 100),1)

##Imagem
include_supplement("Q07MCU.png")
@
\usepackage[utf8]{inputenc}
\begin{question}
Um avião realiza uma curva horizontal, mantendo altitude constante, com raio R = \Sexpr{R} m e velocidade escalar v = \Sexpr{v} m/s. A força de sustentação $F$ é inclinada em relação à vertical, de modo que uma componente equilibre o peso e a outra forneça a força centrípeta. Considerando a massa do avião como de \Sexpr{m} kg, determine a intensidade da força de sustentação $F$. Considere g = 10 m/s².

\begin{figure}[h!]
  \centering
  \includegraphics[height=5cm, keepaspectratio]{Q07MCU.png}
\end{figure}

\end{question}

\begin{solution}
Na curva horizontal, a componente vertical da sustentação equilibra o peso,
\[
  F_y=mg,
\]
e a componente horizontal fornece a força centrípeta,
\[
  F_x=\frac{mv^2}{R}.
\]
Como essas componentes são perpendiculares,
\[
  F=\sqrt{F_x^2+F_y^2}
   =m\sqrt{\left(\frac{v^2}{R}\right)^2+g^2}.
\]
Substituindo,
\[
  F=\Sexpr{m}\sqrt{\left(\frac{\Sexpr{v}^2}{\Sexpr{R}}\right)^2+10^2}
   =\Sexpr{forca}\,\mathrm{N}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{forca}}
%% \exname{Q07MCU}
%% \extol{0.01}
