<<echo=FALSE, results=hide>>=
## DATA GENERATION 
R = sample(seq(90,200,10),1)

## Resposta
f = round((60/(2*pi))*sqrt(10/R), 1)
@
\usepackage[utf8]{inputenc}
\begin{question}
Deseja-se construir uma nave espacial com uma seção rotacional para simular gravidade artificial. A seção terá um raio de \Sexpr{R} metros. Quantas rotações por minuto (RPM) deverá ter essa seção para produzir, na borda externa, uma aceleração centrípeta igual à gravidade terrestre? Considere g = 10 m/s² e arredonde a resposta para uma decimal.

\end{question}

\begin{solution}
Na borda da seção rotacional, a aceleração centrípeta deve reproduzir \(g\):
\[
  a_c=\omega^2R=g.
\]
Logo,
\[
  \omega=\sqrt{\frac{g}{R}}
  =\sqrt{\frac{10}{\Sexpr{R}}}\,\mathrm{rad/s}.
\]
A frequência em hertz é \(f=\omega/(2\pi)\). Convertendo para rotações por minuto,
\[
  f_{rpm}=60\frac{\omega}{2\pi}
         =\Sexpr{f}\,\mathrm{rpm}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{f}}
%% \exname{Q09MCU}
%% \extol{0.01}
