<<echo=FALSE, results=hide>>=
## DATA GENERATION EXAMPLE
R_cm <- sample(5:25,1)
R_m <- R_cm/100
v = sample(2:20,1)

## Resposta
f = round(10*v/R_m, 1)

##Imagem
include_supplement("Q10MCU.png")
@
\usepackage[utf8]{inputenc}
\begin{question}
Anemômetros são instrumentos usados para medir a velocidade do vento. A sua construção mais conhecida é a proposta por Robinson em 1846, que consiste em um rotor com quatro conchas hemisféricas presas por hastes, conforme figura abaixo. Em um anemômetro de Robinson ideal, a velocidade do vento é dada pela velocidade linear das conchas. Se necessário considere $\pi=3$. Arredonde para uma decimal.

\begin{figure}[h!]
  \centering
  \includegraphics[height=5cm, keepaspectratio]{Q10MCU.png}
\end{figure}

Se em um anemômetro a distância entre as conchas e o centro de rotação é r = \Sexpr{R_cm} cm, em um dia cuja velocidade do vento é v = \Sexpr{v} m/s, qual seria a frequência de rotação em RPM?

\end{question}

\begin{solution}
No modelo ideal, a velocidade do vento é igual à velocidade linear das conchas:
\[
  v=\omega r=2\pi f r,
\]
com \(f\) em hertz. Portanto,
\[
  f=\frac{v}{2\pi r}.
\]
Como \(r=\Sexpr{R_cm}\,\mathrm{cm}=\Sexpr{R_m}\,\mathrm{m}\) e \(\pi=3\), a frequência em rpm é
\[
  f_{rpm}=60\frac{\Sexpr{v}}{6\cdot\Sexpr{R_m}}
         =\Sexpr{f}\,\mathrm{rpm}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{f}}
%% \exname{Q10MCU}
%% \extol{0.01}
