<<echo=FALSE, results=hide>>=
# Created by vinibrenobr11 - corrigido por Marcelo C.

# Calorias absorvidas e temperatura do corpo 1
Q1 <- sample(seq(from=100, to=200, by=10),1)
dt1 <- sample(seq(from=1, to=10, by=1),1)

# Calorias absorvidas e temperatura do corpo 2
Q2 <- sample(seq(from=100, to=800, by=20),1)
resp <- round(Q2*dt1/(2*Q1), 1) # massa 2m

@
\usepackage[utf8]{inputenc}
\begin{question}

Quando um corpo de certa massa \textit{m}, formado por determinada matéria, absorve \Sexpr{Q1} cal, eleva sua temperatura em \Sexpr{dt1} °C. Outro corpo, formado pelo mesmo material, tem massa 2\textit{m}. Se esse outro corpo absorver \Sexpr{Q2} cal, em quanto elevará o valor de sua temperatura? \textit{Arredonde sua resposta para 1 casa decimal se necessário}

\end{question}

%% SOLUTION
\begin{solution}
Para o primeiro corpo,
\[
  Q_1=mc\Delta T_1,
\]
portanto
\[
  c=\frac{Q_1}{m\Delta T_1}.
\]

O segundo corpo tem massa \(2m\). Assim,
\[
  Q_2=(2m)c\Delta T_2.
\]
Substituindo a expressão de \(c\),
\[
  Q_2=2m\frac{Q_1}{m\Delta T_1}\Delta T_2.
\]
Logo,
\[
  \Delta T_2=\frac{Q_2\Delta T_1}{2Q_1}
            =\frac{\Sexpr{Q2}\cdot\Sexpr{dt1}}{2\cdot\Sexpr{Q1}}
            =\Sexpr{resp}\,^{\circ}\mathrm{C}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q07CalS}
%% \extol{0.1}
