<<echo=FALSE, results=hide>>=
## Opções
options(scipen=999) ## evita número em notação

## Parâmetros
vol   <- sample(seq(from=4,to=50,by=1),1)
  
## Resposta
resp1 <- round((vol*10^3)*540, digits = 1)/1000
resp2 <- round((vol*10^3)*80, digits = 1)/1000
@
\usepackage[utf8]{inputenc}
\begin{question}
  
A água é muito comum no nosso cotidiano, e sabe-se que ela possui densidade de 1g/cm³ e calor latente de vaporização 540 cal/g e de fusão 80 cal/g. 
  
  \begin{answerlist}
  
    \item A quantidade de calor (em kcal) necessária para evaporar $\Sexpr{vol}$ litros de água é de:
    \item O módulo da quantidade de calor (em kcal) cedida ao solidificar $\Sexpr{vol}$ litros de água é de:
  
  \end{answerlist}
  
\end{question}
  
%% SOLUTION
\begin{solution}
Como a densidade da água é \(1\,\mathrm{g/cm^3}\), \(\Sexpr{vol}\,\mathrm{L}\) correspondem a
\[
  m=\Sexpr{vol}\cdot1000
   =\Sexpr{vol*1000}\,\mathrm{g}.
\]

Durante uma mudança de fase,
\[
  Q=mL.
\]

\begin{answerlist}
  \item Para a vaporização,
  \[
    Q_v=\Sexpr{vol*1000}\cdot540
       =\Sexpr{vol*1000*540}\,\mathrm{cal}
       =\Sexpr{resp1}\,\mathrm{kcal}.
  \]

  \item Na solidificação, a água cede calor. O módulo é
  \[
    |Q_s|=\Sexpr{vol*1000}\cdot80
         =\Sexpr{vol*1000*80}\,\mathrm{cal}
         =\Sexpr{resp2}\,\mathrm{kcal}.
  \]
\end{answerlist}

\end{solution}
  
  
%% META-INFORMATION
%% \extype{cloze}
%% \exclozetype{num|num}
%% \exsolution{\Sexpr{resp1}|\Sexpr{resp2}}
%% \exname{Q14CalL}
%% \extol{1|1}