<<echo=FALSE, results=hide>>=
#Programado por: Jmduly
  
mass   <- sample(seq(from=20,to=50,by=1),1)
  
lat   <- sample(seq(from=35,to=60,by=1),1)
  
resp1 <- round((mass)*(lat), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}

\begin{question}
  
Um corpo de massa $\Sexpr{mass}$ g encontra-se em sua temperatura de fusão. Durante a fusão completa, seu calor latente de fusão é $\Sexpr{lat}$ cal/g. Qual é a quantidade de calor recebida pelo corpo durante essa mudança de fase?

\end{question}
  
%% SOLUTION
\begin{solution}
Durante a fusão, a temperatura permanece constante e o calor recebido é latente:
\[
  Q=mL.
\]
Assim,
\[
  Q=\Sexpr{mass}\cdot\Sexpr{lat}
   =\Sexpr{resp1}\,\mathrm{cal}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q16CalL}
%% \extol{1|}