<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
mass  <- sample(seq(from=20,to=80,by=1),1)
  
calor <- sample(seq(from=200,to=5000,by=10),1)
  
resp1 <- round((calor)/(mass), digits = 1)
  
@

\usepackage[utf8]{inputenc}
  
\begin{question}
  
Um corpo de massa $\Sexpr{mass}$ g encontra-se inicialmente no estado líquido, em sua temperatura de solidificação. Ao solidificar completamente, ele cede $\Sexpr{calor}$ cal ao ambiente. Determine, em módulo, o calor latente de fusão do material.

\end{question}
  
%% SOLUTION
\begin{solution}
Na solidificação completa, o módulo do calor cedido é
\[
  |Q|=mL.
\]
O calor latente de solidificação tem o mesmo módulo do calor latente de fusão. Portanto,
\[
  L=\frac{|Q|}{m}
   =\frac{\Sexpr{calor}}{\Sexpr{mass}}
   =\Sexpr{resp1}\,\mathrm{cal/g}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q17CalL}
%% \extol{1}