<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  mass1 <- sample(seq(from=200,to=1000,by=1),1)
  
  time1 <- sample(seq(from=20,to=100,by=1),1)
  
  temp1 <- sample(seq(from=150,to=300,by=1),1)
  
  resp1 <- round((mass1*2*10^-2*temp1)*4.186/(time1), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Uma fonte de potência constante é utilizada para aquecer $\Sexpr{mass1}$ g de aço de $0$ °C até $\Sexpr{temp1}$ °C. Sendo o calor específico do aço $0,020$ cal/g.°C, $1$ cal $=4,186$ J e o processo realizado em $\Sexpr{time1}$ s, determine a potência térmica da fonte em watts.

\end{question}
  
  %% SOLUTION
\begin{solution}
A quantidade de calor necessária é
\[
  Q=mc\Delta T
   =\Sexpr{mass1}\cdot0{,}020\cdot\Sexpr{temp1}
   =\Sexpr{mass1*0.02*temp1}\,\mathrm{cal}.
\]

Em joules,
\[
  E=\Sexpr{mass1*0.02*temp1}\cdot4{,}186
   =\Sexpr{mass1*0.02*temp1*4.186}\,\mathrm{J}.
\]

A potência é
\[
  P=\frac{E}{\Delta t}
   =\frac{\Sexpr{mass1*0.02*temp1*4.186}}{\Sexpr{time1}}
   =\Sexpr{resp1}\,\mathrm{W}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q20CalS}
%% \extol{0.01}