<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  vol1 <- sample(seq(from=1,to=3,by=1),1)
  
  vol2 <- sample(seq(from=500,to=1500,by=1),1)
  
  temp1 <- 100
  
  temp2 <- sample(seq(from=5,to=25,by=1),1)
  
  resp1 <- round((vol1*10^3*temp1 + vol2*temp2)/(vol1*10^3 + vol2), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
  Em uma cozinha, uma chaleira com $\Sexpr{vol1}$ L de água ferve. Para que ela pare, são adicionados $\Sexpr{vol2}$ mL de água à $\Sexpr{temp2}$ °C. Qual a temperatura do equilíbrio do sistema?

\end{question}
  
%% SOLUTION
\begin{solution}
Como as duas porções são de água, possuem o mesmo calor específico. A massa da água quente é
\[
  m_1=\Sexpr{vol1}\,\mathrm{L}
     =\Sexpr{vol1*1000}\,\mathrm{g},
\]
enquanto a massa adicionada é \(m_2=\Sexpr{vol2}\,\mathrm{g}\).

Sem perdas de calor,
\[
  m_1c(T_f-100)+m_2c(T_f-\Sexpr{temp2})=0.
\]
Cancelando \(c\),
\[
  T_f=
  \frac{m_1\cdot100+m_2\cdot\Sexpr{temp2}}
       {m_1+m_2}.
\]

Portanto,
\[
  T_f=
  \frac{\Sexpr{vol1*1000}\cdot100+
        \Sexpr{vol2}\cdot\Sexpr{temp2}}
       {\Sexpr{vol1*1000}+\Sexpr{vol2}}
  =\Sexpr{resp1}\,^{\circ}\mathrm{C}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q24TroCal}
%% \extol{0.01|}