<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=250,to=320,by=1),1)
  
  vol1   <- sample(seq(from=12,to=60,by=1),1)
  
  trab1  <- sample(seq(from=1,to=5,by=1),1)
  
  resp1  <- round((trab1*1000/press1+vol1), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Um gás ideal de volume $\Sexpr{vol1}$ m³ sofre uma transformação, permanecendo sob pressão constante igual a $\Sexpr{press1}$ Pa. Qual é o volume do gás quando o trabalho realizado por ele for $\Sexpr{trab1}$ kJ?

\end{question}
  
\begin{solution}
Em uma transformação isobárica, o trabalho realizado pelo gás é
\[
  W=P(V_f-V_i).
\]

O trabalho fornecido no enunciado está em quilojoules:
\[
  W=\Sexpr{trab1}\,\mathrm{kJ}
   =\Sexpr{trab1*1000}\,\mathrm{J}.
\]

Assim,
\[
  V_f=V_i+\frac{W}{P}
     =\Sexpr{vol1}
      +\frac{\Sexpr{trab1*1000}}{\Sexpr{press1}}
     =\Sexpr{resp1}\,\mathrm{m^3}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q49Termod}
%% \extol{0.01}

