<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=100000,to=150000,by=1),1)
  
  vol1   <- sample(seq(from=12,to=20,by=1),1)
  
  vol2   <- sample(seq(from=1,to=10,by=1),1)
  
  mols1  <- sample(seq(from=12,to=50,by=1),1)
  
  resp1  <- round((press1*(vol1-vol2)), digits = 1)
    
@

\usepackage[utf8]{inputenc}

\begin{question}
  
Um gás encontra-se em um recipiente com êmbolo, sob pressão constante igual à pressão atmosférica, ocupando inicialmente $\Sexpr{vol1}$ m³. Ao empurrar o êmbolo, seu volume passa a $\Sexpr{vol2}$ m³. A pressão é $\Sexpr{press1}$ N/m². Qual é o trabalho realizado sobre o gás?

\end{question}
  
%% SOLUTION
\begin{solution}
O trabalho realizado pelo gás em uma transformação isobárica é
\[
  W_{\mathrm{gás}}=P(V_f-V_i).
\]
Como ocorre compressão, \(V_f<V_i\), esse trabalho é negativo. O trabalho realizado \emph{sobre} o gás tem o mesmo módulo e sinal positivo:
\[
  W_{\mathrm{sobre}}=P(V_i-V_f).
\]

Portanto,
\[
  W_{\mathrm{sobre}}
  =\Sexpr{press1}\,
   (\Sexpr{vol1}-\Sexpr{vol2})
  =\Sexpr{resp1}\,\mathrm{J}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q50Termod}
%% \extol{0.01}