<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=20,to=100,by=1),1)
  
  mols1   <- sample(seq(from=1,to=3,by=0.5),1)
  
  resp1  <- round((3/2*mols1*8.31*(temp1+273)), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere $\Sexpr{mols1}$ mols de um gás ideal monoatômico na temperatura de $\Sexpr{temp1}$ °C e R=8,31 J/mol.K. Qual a energia interna do gás?

\end{question}
  
%% SOLUTION
\begin{solution}
Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}nRT.
\]

A temperatura absoluta é
\[
  T=\Sexpr{temp1}+273
   =\Sexpr{temp1+273}\,\mathrm{K}.
\]

Assim,
\[
  U=\frac{3}{2}\,
    \Sexpr{mols1}\cdot8{,}31\cdot\Sexpr{temp1+273}
   =\Sexpr{resp1}\,\mathrm{J}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q55Termod}
%% \extol{0.01}