<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=0,to=60,by=1),1)
  
  temp2  <- sample(seq(from=80,to=190,by=1),1)
  
  u      <- sample(seq(from=3000,to=15000,by=1500),1)
  
  resp1  <- round(((2/3*u)/(((temp2+273)-(temp1+273))*8.31)), digits = 1)

@
  
\usepackage[utf8]{inputenc}
  
\begin{question}

Considere um gás ideal monoatômico na temperatura de $\Sexpr{temp1}$ °C que varia para $\Sexpr{temp2}$ °C, e a variação da energia interna é $\Sexpr{u}$ J. Dados: R=8,31 J/mol.K. Quanto(s) mols há do gás?

\end{question}
  
%% SOLUTION
\begin{solution}
Para um gás ideal monoatômico,
\[
  \Delta U=\frac{3}{2}nR\Delta T.
\]

A variação de temperatura é
\[
  \Delta T=\Sexpr{temp2}-\Sexpr{temp1}
          =\Sexpr{temp2-temp1}\,\mathrm{K}.
\]

Isolando o número de mols,
\[
  n=\frac{2\Delta U}{3R\Delta T}
   =\frac{2\cdot\Sexpr{u}}
          {3\cdot8{,}31\cdot\Sexpr{temp2-temp1}}
   =\Sexpr{resp1}\,\mathrm{mol}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q57Termod}
%% \extol{0.01}
