<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=273,to=373,by=1),1)
  
  u      <- sample(seq(from=9000,to=21000,by=1500),1)
  
  resp1  <- round(((2/3*u)/((temp1)*8.31)), digits = 1)

@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere um gás ideal monoatômico na temperatura de $\Sexpr{temp1}$ K e a energia interna $\Sexpr{u}$ J. Dado R=8,31 J/mol.K, quanto(s) mols há do gás?

\end{question}
  
%% SOLUTION
\begin{solution}
Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}nRT.
\]

Isolando \(n\),
\[
  n=\frac{2U}{3RT}.
\]
Substituindo \(U=\Sexpr{u}\,\mathrm{J}\) e
\(T=\Sexpr{temp1}\,\mathrm{K}\),
\[
  n=
  \frac{2\cdot\Sexpr{u}}
       {3\cdot8{,}31\cdot\Sexpr{temp1}}
  =\Sexpr{resp1}\,\mathrm{mol}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q58Termod}
%% \extol{0.01}
