<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=0.5,to=3,by=0.5),1)
  
  vol1   <- sample(seq(from=3,to=12,by=1),1)
  
  resp1  <- round((3/2*(press1*10^5)*vol1), digits = 1)

@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere $\Sexpr{vol1}$ m³ de um gás ideal monoatômico sob pressão de $\Sexpr{press1}$ atm. Adote $1\,\mathrm{atm}=10^5\,\mathrm{Pa}$. Qual é a energia interna do gás?

\end{question}
  
%% SOLUTION
\begin{solution}
Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}nRT.
\]
Usando \(PV=nRT\),
\[
  U=\frac{3}{2}PV.
\]

A pressão em pascals é
\[
  P=\Sexpr{press1}\cdot10^5
   =\Sexpr{press1*1e5}\,\mathrm{Pa}.
\]

Logo,
\[
  U=\frac{3}{2}\,
    \Sexpr{press1*1e5}\cdot\Sexpr{vol1}
   =\Sexpr{resp1}\,\mathrm{J}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q59Termod}
%% \extol{0.01}
