<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=3000,to=7000,by=250),1)
  
  vol1   <- sample(seq(from=3,to=12,by=1),1)
  
  resp1  <- round(((3/2)*press1*vol1), digits = 1)

@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere $\Sexpr{vol1}$ m³ de um gás ideal monoatômico sob pressão de $\Sexpr{press1}$ Pa. Qual é a energia interna do gás?

\end{question}
  
\begin{solution}
Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}nRT.
\]
Como \(PV=nRT\),
\[
  U=\frac{3}{2}PV.
\]

Portanto,
\[
  U=\frac{3}{2}\,
    \Sexpr{press1}\cdot\Sexpr{vol1}
   =\Sexpr{resp1}\,\mathrm{J}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q60Termod}
%% \extol{0.01|}
