<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=5000,to=17000,by=500),1)
  
  u      <- sample(seq(from=300000,to=450000,by=10000),1)
  
  resp1  <- round((2/3*u)/(press1), digits = 1)

@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere um gás ideal monoatômico sob pressão de $\Sexpr{press1}$ Pa e com energia interna de $\Sexpr{u}$ J. Qual é o volume ocupado pelo gás?

\end{question}
  
%% SOLUTION
\begin{solution}
Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}PV.
\]

Isolando o volume,
\[
  V=\frac{2U}{3P}.
\]

Substituindo,
\[
  V=
  \frac{2\cdot\Sexpr{u}}
       {3\cdot\Sexpr{press1}}
  =\Sexpr{resp1}\,\mathrm{m^3}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q62Termod}
%% \extol{0.01}
