<<echo=FALSE, results=hide>>=
# Programado por: Jmduly

nota_cient <- function(x,digits) {
  if (x==0) return("0")
  ord <- floor(log(abs(x),10))
  x <- x / 10^ord
  if (!missing(digits)) x <- format(x,digits=digits)
  if (ord==0) return(as.character(x))
  return(paste(x,"\\\\times 10^{",ord,"}",sep=""))
}

vol1 <- sample(seq(from=5000000,to=20000000,by=5000000),1)
u <- sample(seq(from=300000,to=45000000,by=300000),1)

resp1 <- round(((2/3*u)/(vol1*10^-6))/10^6, digits = 2)
@

\usepackage[utf8]{inputenc}

\begin{question}

Considere um gás ideal monoatômico de volume $\Sexpr{nota_cient(vol1)}$ cm³ e energia interna $\Sexpr{u}$ J. Qual é a pressão do gás em MPa? OBS: apresente o resultado com duas decimais.

\end{question}

\begin{solution}

Para um gás ideal monoatômico,
\[
  U=\frac{3}{2}PV.
\]
Logo,
\[
  P=\frac{2U}{3V}.
\]

O volume deve ser convertido para unidades do SI. Como
\(1\,\mathrm{cm^3}=10^{-6}\,\mathrm{m^3}\),
\[
  V=\Sexpr{nota_cient(vol1)}\cdot10^{-6}
   =\Sexpr{vol1*1e-6}\,\mathrm{m^3}.
\]

Assim,
\[
  P=
  \frac{2\cdot\Sexpr{u}}
       {3\cdot\Sexpr{vol1*1e-6}}
  \,\mathrm{Pa}.
\]

Como \(1\,\mathrm{MPa}=10^6\,\mathrm{Pa}\),
\[
  P=\Sexpr{resp1}\,\mathrm{MPa}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q63Termod}
%% \extol{0.01}
