<<echo=FALSE, results=hide>>=
##PROGRAMADO POR: CARLOS S.
aleat = sample(1:5)

questions <- numeric(5)
solutions <- logical(5)

questions[aleat[1]] <- "A energia térmica de um corpo está associada à energia microscópica de suas partículas."
questions[aleat[2]] <- "Dois corpos atingem o equilíbrio térmico quando suas temperaturas se tornam iguais."
questions[aleat[3]] <- "Mantidas a quantidade de matéria e as condições do sistema, uma alteração de temperatura está associada a uma alteração de sua energia térmica."
questions[aleat[4]] <- "Somente podemos chamar de calor a energia térmica em trânsito; assim, não podemos afirmar que um corpo contém calor."
questions[aleat[5]] <- "A quantidade de calor que um corpo contém depende de sua temperatura e do número de partículas nele existentes."

solutions[aleat[1]] <- FALSE
solutions[aleat[2]] <- FALSE
solutions[aleat[3]] <- FALSE
solutions[aleat[4]] <- FALSE
solutions[aleat[5]] <- TRUE

@
\usepackage[utf8]{inputenc}
\begin{question}

Analise as proposições e indique a falsa.

<<echo=FALSE, results=hide, results=tex>>=
answerlist(questions)
@

\end{question}

\begin{solution}
Calor não é uma quantidade armazenada em um corpo. Em Física, chamamos de calor a energia transferida entre sistemas em razão de uma diferença de temperatura.

Por isso, a proposição falsa é a que afirma que um corpo ``contém calor''. Um corpo possui energia interna ou energia térmica, mas calor designa energia em trânsito.

<<echo=FALSE, results=hide, results=tex>>=
answerlist(ifelse(solutions, paste("\\textbf{", questions, "}", sep=""), questions))
@

\end{solution}

%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q04QuizCal}
%% \exusepackage[utf8]{inputenc}
