<<echo=FALSE, results=hide>>=
##PROGRAMADO POR: CARLOS SANTANA, em 30 de julho de 2017.
aleat = sample(1:5)

questions <- numeric(5)
solutions <- logical(5)

questions[aleat[1]] <- "Ta > Tb"
questions[aleat[2]] <- "Ta = Tb"
questions[aleat[3]] <- "Ta < Tb"
questions[aleat[4]] <- "As moléculas dos corpos cessam suas vibrações"
questions[aleat[5]] <- "Nada se pode afirmar"

solutions[aleat[1]] <- FALSE
solutions[aleat[2]] <- TRUE
solutions[aleat[3]] <- FALSE
solutions[aleat[4]] <- FALSE
solutions[aleat[5]] <- FALSE

@
\usepackage[utf8]{inputenc}
\begin{question}

Dois corpos A e B de massas $m_a$ e $m_b$ diferentes estão inicialmente a temperaturas $T_a$ e $T_b$ diferentes. Num dado instante, eles são colocados em contato térmico. Chamando de $T'_a$ e $T'_b$ as temperaturas de equilíbrio térmico dos corpos A e B respectivamente, podemos afirmar que:

<<echo=FALSE, results=hide, results=tex>>=
answerlist(questions)
@

\end{question}

\begin{solution}
No equilíbrio térmico, não há transferência líquida de energia entre os corpos. A condição para isso é que ambos atinjam a mesma temperatura final.

Assim,
\[
  T'_a=T'_b.
\]

As massas diferentes influenciam o valor da temperatura de equilíbrio, mas não alteram o fato de que os dois corpos terminam com a mesma temperatura.

<<echo=FALSE, results=hide, results=tex>>=
answerlist(ifelse(solutions, paste("\\textbf{", questions, "}", sep=""), questions))
@

\end{solution}

%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q08Cal}
%% \exusepackage[utf8]{inputenc}