<<echo=FALSE, results=hide>>=
##PROGRAMADO POR: CARLOS SANTANA, em 30 de julho de 2017.
aleat = sample(1:5)

questions <- numeric(5)
solutions <- logical(5)

questions[aleat[1]] <- "Ta > Tb"
questions[aleat[2]] <- "Ta = Tb"
questions[aleat[3]] <- "Ta < Tb"
questions[aleat[4]] <- "As moléculas dos corpos cessam suas vibrações"
questions[aleat[5]] <- "Nada se pode afirmar"

solutions[aleat[1]] <- FALSE
solutions[aleat[2]] <- TRUE
solutions[aleat[3]] <- FALSE
solutions[aleat[4]] <- FALSE
solutions[aleat[5]] <- FALSE

@
\usepackage[utf8]{inputenc}
\begin{question}

Dois corpos A e B de massas 𝒎𝑨 e 𝒎𝑩 diferentes estão inicialmente a temperaturas T𝑨 e T𝑩 diferentes. Num dado instante, eles são colocados em contato térmico. Chamando de T′𝑨 e T′𝑩 as temperaturas de equilíbrio térmico dos corpos A e B respectivamente, podemos afirmar que:
<<echo=FALSE, results=hide, results=tex>>=
answerlist(questions)
@

\end{question}

\begin{solution}
<<echo=FALSE, results=hide, results=tex>>=
answerlist(
  paste("\\textbf{", ifelse(solutions, "Verdadeiro", "Falso"), "}"))
@



\end{solution}

%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q05TestDilatL}
%% \exusepackage[utf8]{inputenc}