<<echo=FALSE, results=hide>>=

# Created by vinibrenobr11 on 29/07/2017

aleat = sample(1:5)

questions <- numeric(5)
solutions <- logical(5)

questions[aleat[1]] <- "Permite a entrada da luz solar, mas não permite a saída dos raios ultravioleta emitidos pelas plantas e pelo solo da estufa."
questions[aleat[2]] <- "É transparente à luz solar, mas opaco aos raios infravermelhos emitidos pelas plantas e pelo solo da estufa."
questions[aleat[3]] <- "É opaco à luz solar mas transparente aos raios infravermelhos emitidos pelas plantas e pelo solo da estufa."
questions[aleat[4]] <- "Ao ser iluminado pela luz solar, produz calor, aquecendo as plantas."
questions[aleat[5]] <- "Não permite a entrada da luz solar, mas permite a saída dos raios ultravioleta, emitidos pelas plantas e pelo solo da estufa."

solutions[aleat[1]] <- FALSE
solutions[aleat[2]] <- TRUE
solutions[aleat[3]] <- FALSE
solutions[aleat[4]] <- FALSE
solutions[aleat[5]] <- FALSE
@
\begin{question}

  (Vunesp-SP) Uma estufa para a planta\c{c}\~ao de flores \'e feita com teto e paredes de vidro comum. Dessa forma, durante o dia, o ambiente interno da estufa \'e mantido a uma temperatura mais alta do que o externo. Isso se d\'a porque o vidro comum:

<<echo=FALSE, results=hide, results=tex>>=
answerlist(questions)
@
  
\end{question}

\begin{solution}
A radiação solar atravessa o vidro em grande parte nas faixas visível e de pequeno comprimento de onda e aquece as superfícies no interior da estufa.

Essas superfícies aquecidas emitem radiação principalmente no infravermelho. O vidro comum é menos transparente a parte dessa radiação infravermelha, dificultando a perda de energia para o exterior.

Portanto, entre as alternativas apresentadas, a correta é a que afirma que o vidro é \textbf{transparente à luz solar, mas relativamente opaco à radiação infravermelha emitida no interior}.

<<echo=FALSE, results=hide, results=tex>>=
answerlist(ifelse(solutions, paste("\\textbf{", questions, "}", sep=""), questions))
@

\end{solution}

%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q09Cal}