<<echo=FALSE, results=hide>>=
  ##feito por Matheus Bertos
  ##gera valores
  temp <- sample(seq(from=-10,to=12,by=0.5),1)
  resp <- round((temp*1.8)+32, digits = 1)
  ##gera a resposta

  aleat = sample(5)
  
  questions <- numeric(5)
  solutions <- logical(5)
  
  questions[aleat[1]] <- resp - 2*1.8
  questions[aleat[2]] <- resp 
  questions[aleat[3]] <- resp + 5
  questions[aleat[4]] <- resp + 2*1.8
  questions[aleat[5]] <- resp - 10
  
  solutions[aleat[1]] <-  FALSE
  solutions[aleat[2]] <-  TRUE
  solutions[aleat[3]] <-  FALSE
  solutions[aleat[4]] <-  FALSE
  solutions[aleat[5]] <-  FALSE
@

\usepackage[portuguese]{babel}

\begin{question}

   Em um dia frio, um termômetro na escala Celsius assinala \Sexpr{temp} °C para o meio ambiente. Um outro termômetro graduado em Fahrenheit está marcando, em °F,

<<echo=FALSE, results=hide, results=tex>>=
    answerlist(questions)
@
\end{question}

\begin{solution}
A relação entre as escalas Celsius e Fahrenheit é
\[
  T_F=1{,}8T_C+32.
\]

Para a temperatura sorteada,
\[
  T_F=1{,}8\,(\Sexpr{temp})+32
     =\Sexpr{resp}\,^{\circ}\mathrm{F}.
\]

Portanto, a alternativa correta é \(\Sexpr{resp}\,^{\circ}\mathrm{F}\).

<<echo=FALSE, results=hide, results=tex>>=
answerlist(ifelse(solutions, paste("\\textbf{", questions, "}", sep=""), questions))
@

\end{solution}
%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q11Term}
%% \exusepackage[utf8]{inputenc}
