<<echo=FALSE, results=hide>>=
##MARCELO C.

dtc <- sample(seq(from=5,to=70,by=1),1) 

resp1 <- dtc     
resp2 <- 1.8*dtc 
@

\begin{question}

Quando um term\^ometro na escala Celsius sofrer uma varia\c{c}\~ao de $\Sexpr{dtc}$ graus em sua temperatura, qual ser\'a a correspondente varia\c{c}\~ao de temperatura para:

\begin{answerlist}
\item Um term\^ometro graduado na escala Kelvin

\item Um term\^ometro graduado na escala Fahrenheit.

\end{answerlist}

\end{question}

%% SOLUTION
\begin{solution}
Uma variação de temperatura de \(1\,^{\circ}\mathrm{C}\) corresponde numericamente a \(1\,\mathrm{K}\). Portanto,
\[
  \Delta T_K=\Delta T_C=\Sexpr{dtc}\,\mathrm{K}.
\]

Já entre Celsius e Fahrenheit,
\[
  \Delta T_F=1{,}8\,\Delta T_C.
\]
Assim,
\[
  \Delta T_F=1{,}8\cdot\Sexpr{dtc}
             =\Sexpr{resp2}\,^{\circ}\mathrm{F}.
\]

\begin{answerlist}
  \item \Sexpr{resp1} K
  \item \Sexpr{resp2} °F
\end{answerlist}

\end{solution}

%% META-INFORMATION
%% \extype{cloze}
%% \exclozetype{num|num}
%% \exsolution{\Sexpr{resp1}|\Sexpr{resp2}}
%% \exname{Q13term}
%% \extol{0.01|0.01}
