<<echo=FALSE, results=hide>>=
##PROGRAMADO POR: CARLOS SANTANA, em 14 de Maio de 2017.
##FONTE: Unesp

v <- sample(seq(from=0.1,to=2,by=0.1),1)
t <- sample(seq(from=10,to=90,by=5), 1)

respa <- 0.5*v
respb <- respa*t

@

\begin{question}
Considere: sen(30°) = 0,5

(Unesp) A escada rolante que liga a plataforma de uma estação subterrânea de metrô ao nível da rua move-se com velocidade constante de \Sexpr{v} m/s.
\begin{answerlist}

\item Sabendo-se que a escada tem uma inclinação de 30° em relação à horizontal, determine a componente vertical de sua velocidade. 

\item Sabendo-se que o tempo necessário para um passageiro seja transportado pela escada, do nível da plataforma ao nível da rua, é de \Sexpr{t} segundos, determine a que profundidade se encontra o nível da plataforma em relação ao nível da rua.

\end{answerlist}


\end{question}

%% SOLUTION
\begin{solution}
A componente vertical da velocidade é
\[
  v_y=v\sin30^\circ.
\]
Como \(\sin30^\circ=0{,}5\),
\[
  v_y=\Sexpr{v}\cdot0{,}5
     =\Sexpr{respa}\,\mathrm{m/s}.
\]

A profundidade corresponde ao deslocamento vertical realizado durante \(\Sexpr{t}\,\mathrm{s}\):
\[
  h=v_y t
   =\Sexpr{respa}\cdot\Sexpr{t}
   =\Sexpr{respb}\,\mathrm{m}.
\]

\begin{answerlist}
  \item \Sexpr{respa} m/s
  \item \Sexpr{respb} m
\end{answerlist}

\end{solution}

%% META-INFORMATION
%% \extype{cloze}
%% \exclozetype{num|num}
%% \exsolution{\Sexpr{respa}|\Sexpr{respb}}
%% \exname{Q014Velm}
%% \extol{0.1|0.1}