<<echo=FALSE, results=hide>>=
##PROGRAMADO POR: MARCELO C.

v1 <- sample(seq(from=20,to=30,by=1),1)
v2 <- sample(seq(from=40,to=80,by=1),1)

resp <- round(2*v1*v2/(v1+v2),1)
options(OutDec=",")
@

\begin{question}

Uma moto percorre a primeira metade de um percurso de 4 km com velocidade constante de $\Sexpr{v1}$ km/h e a segunda metade com $\Sexpr{v2}$ km/h. Calcule a velocidade escalar média da moto no percurso todo em km/h. Arredonde sua resposta final para 1 decimal (utilize maior precis\~ao
nos passos intermedi\'arios).

\end{question}

%% SOLUTION
\begin{solution}
Como as duas metades do percurso têm a mesma distância, não podemos calcular a média aritmética simples das velocidades. Seja \(d\) a distância de cada metade.

Os tempos gastos são
\[
  t_1=\frac{d}{v_1},\qquad t_2=\frac{d}{v_2}.
\]
A velocidade média no percurso total \(2d\) é
\[
  v_m=\frac{2d}{d/v_1+d/v_2}
     =\frac{2v_1v_2}{v_1+v_2}.
\]
Substituindo,
\[
  v_m=\frac{2\cdot\Sexpr{v1}\cdot\Sexpr{v2}}
             {\Sexpr{v1}+\Sexpr{v2}}
     =\Sexpr{resp}\,\mathrm{km/h}.
\]

\end{solution}

<<echo=FALSE, results=hide>>=
options(OutDec=".")
@
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp}}
%% \exname{Q08Velm}
%% \extol{0.002}
