<<echo=FALSE, results=hide>>=
##Programado por:Matheus V

##gera questoes
dist <- sample(seq(from=20,to=80,by=20),1)

resp <- (dist/80)

aleat <- sample(1:5)
questions <- numeric(5)
solutions <- logical(5)

  questions[aleat[1]] <- resp+0.5
  solutions[aleat[1]] <- FALSE
  
  questions[aleat[2]] <- resp+0.2
  solutions[aleat[2]] <- FALSE
  
  questions[aleat[3]] <- resp-0.2
  solutions[aleat[3]] <- FALSE
  
  questions[aleat[4]] <- resp
  solutions[aleat[4]] <- TRUE
  
  questions[aleat[5]] <- resp-0.1
  solutions[aleat[5]] <- FALSE
@
\usepackage[utf8]{inputenc}
\begin{question}
Um automóvel percorre uma estrada com função horária s=-\Sexpr{dist}+80t, onde s é dado em km e t em horas. O automóvel passa pelo km zero após:

<<echo=FALSE, results=hide, results=tex>>=
answerlist(questions)           
@
\end{question}

\begin{solution}
A função horária é
\[
  s(t)=-\Sexpr{dist}+80t.
\]
Para encontrar o instante em que o automóvel passa pelo km zero, fazemos \(s=0\):
\[
  0=-\Sexpr{dist}+80t.
\]
Logo,
\[
  t=\frac{\Sexpr{dist}}{80}
   =\Sexpr{resp}\,\mathrm{h}.
\]

<<echo=FALSE, results=hide, results=tex>>=
answerlist(ifelse(solutions, paste("\\textbf{", questions, "}", sep=""), questions))
@

\end{solution}

%% META-INFORMATION
%% \extype{schoice}
%% \exsolution{\Sexpr{mchoice2string(solutions, single = TRUE)}}
%% \exname{Q11}