<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=15,to=25,by=1),1)
  
  temp2  <- sample(seq(from=30,to=40,by=1),1)
  
  vol1   <- sample(seq(from=21,to=32,by=1),1)

  press1 <- sample(seq(from=1,to=5,by=1),1)

  resp1  <- round(press1*(temp2+273)/(temp1+273), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
  Um recipiente indeformável, hermeticamente fechado, contém $\Sexpr{vol1}$ litros de um gás perfeito a $\Sexpr{temp1}$ °C, suportando a pressão de $\Sexpr{press1}$ atmosferas. A temperatura do gás é aumentada até atingir $\Sexpr{temp2}$ °C. Calcule a pressão final do gás. OBS: apresente o resultado com uma decimal.

\end{question}
  
%% SOLUTION
\begin{solution}
O recipiente é indeformável e hermeticamente fechado, portanto o volume e a quantidade de gás permanecem constantes. Assim,
\[
  \frac{P_1}{T_1}=\frac{P_2}{T_2}.
\]

As temperaturas absolutas são
\[
  T_1=\Sexpr{temp1}+273=\Sexpr{temp1+273}\,\mathrm{K},
\]
e
\[
  T_2=\Sexpr{temp2}+273=\Sexpr{temp2+273}\,\mathrm{K}.
\]

Portanto,
\[
  P_2=
  \Sexpr{press1}
  \frac{\Sexpr{temp2+273}}{\Sexpr{temp1+273}}
  =\Sexpr{resp1}\,\mathrm{atm}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q40Gas}
%% \extol{0.01}
