<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=30,to=60,by=1),1)
  
  temp2  <- sample(seq(from=90,to=120,by=1),1)
  
  vol1   <- sample(seq(from=5,to=40,by=1),1)
  
  resp1  <- round((vol1*(temp2+273))/(temp1+273), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Um gás de volume $\Sexpr{vol1}$ m³ à temperatura de $\Sexpr{temp1}$ °C é aquecido até a temperatura de $\Sexpr{temp2}$ °C. Qual será o volume ocupado por ele, se esta transformação acontecer sob pressão constante? OBS: apresente o resultado com uma casa decimal.

\end{question}
  
%% SOLUTION
\begin{solution}
Como a transformação ocorre sob pressão constante,
\[
  \frac{V_1}{T_1}=\frac{V_2}{T_2}.
\]

Convertendo as temperaturas para kelvin,
\[
  T_1=\Sexpr{temp1}+273=\Sexpr{temp1+273}\,\mathrm{K},
\]
\[
  T_2=\Sexpr{temp2}+273=\Sexpr{temp2+273}\,\mathrm{K}.
\]

Logo,
\[
  V_2=
  \Sexpr{vol1}
  \frac{\Sexpr{temp2+273}}{\Sexpr{temp1+273}}
  =\Sexpr{resp1}\,\mathrm{m^3}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q42Gas}
%% \extol{0.1}
