<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=273,to=303,by=1),1)
  
  press1 <- sample(seq(from=1,to=5,by=1),1)
  resp1  <- round((0.082*temp1)/press1, digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Considere 1 mol de um gás ideal à temperatura de $\Sexpr{temp1}$ K e pressão de $\Sexpr{press1}$ atm. Dado: $R=0{,}082\,\mathrm{atm\,L/(mol\,K)}$. Determine o volume molar do gás.

\end{question}
  
%% SOLUTION
\begin{solution}
Pela equação de estado do gás ideal,
\[
  PV=nRT.
\]

Para \(n=1\,\mathrm{mol}\), o volume encontrado é justamente o volume molar:
\[
  V_m=\frac{RT}{P}.
\]

Substituindo,
\[
  V_m=
  \frac{0{,}082\cdot\Sexpr{temp1}}
       {\Sexpr{press1}}
  =\Sexpr{resp1}\,\mathrm{L/mol}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q45Gas}
%% \extol{0.01}
