<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  temp1  <- sample(seq(from=100,to=200,by=1),1)
  
  press1 <- sample(seq(from=1,to=5,by=1),1)
  
  vol1   <- sample(seq(from=90,to=120,by=1),1)
  
  resp1  <- round((press1*vol1)/(0.082*temp1), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Um gás ideal ocupa $\Sexpr{vol1}$ litros, sob pressão de $\Sexpr{press1}$ atm e à temperatura de $\Sexpr{temp1}$ K. Dado: $R=0{,}082\,\mathrm{atm\,L/(mol\,K)}$. Determine o número de mols desse gás.

\end{question}
  
%% SOLUTION
\begin{solution}
Pela equação de estado do gás ideal,
\[
  PV=nRT.
\]

Isolando a quantidade de matéria,
\[
  n=\frac{PV}{RT}.
\]

Substituindo,
\[
  n=
  \frac{\Sexpr{press1}\cdot\Sexpr{vol1}}
       {0{,}082\cdot\Sexpr{temp1}}
  =\Sexpr{resp1}\,\mathrm{mol}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q46Gas}
%% \extol{0.01}

