<<echo=FALSE, results=hide>>=
  #Programado por: Jmduly
  
  press1 <- sample(seq(from=2,to=8,by=1),1)
  
  vol1   <- sample(seq(from=90,to=150,by=1),1)
  
  mols1  <- sample(seq(from=1,to=5,by=1),1)
  
  resp1  <- round((press1*vol1)/(0.082*mols1), digits = 1)
  
@
  
\usepackage[utf8]{inputenc}
  
\begin{question}
  
Uma amostra de $\Sexpr{mols1}$ mol de gás ideal ocupa um volume de $\Sexpr{vol1}$ litros e está a uma pressão de $\Sexpr{press1}$ atm. Determine a temperatura do gás. Dado: R = 0,082 atm.L/mol.K

\end{question}
  
%% SOLUTION
\begin{solution}
Pela equação de estado do gás ideal,
\[
  PV=nRT.
\]

Isolando a temperatura,
\[
  T=\frac{PV}{nR}.
\]

Substituindo,
\[
  T=
  \frac{\Sexpr{press1}\cdot\Sexpr{vol1}}
       {\Sexpr{mols1}\cdot0{,}082}
  =\Sexpr{resp1}\,\mathrm{K}.
\]

\end{solution}
  
%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q47Gas}
%% \extol{0.01|}

