<<echo=FALSE, results=hide>>=
##Programado por:Matheus V
## Parâmetros
massa <- sample(seq(from=2,to=10,by=2),1)
velocidade <- sample(seq(from=5,to=15,by=1),1)
distancia <- sample(seq(from=20,to=30,by=2),1)

## Respostas
resp1 <- round(massa*(velocidade^2)/2, 1)
resp2 <- round(resp1/distancia, digits = 2)

## Figuras

@
\usepackage[portuguese]{babel}

\begin{question}
 
      (Unicamp) Sob a ação de uma força constante, um corpo de massa m = \Sexpr{massa} kg adquire, a partir do repouso, a velocidade de \Sexpr{velocidade} m/s. 

  \begin{answerlist}

    \item Qual é trabalho realizado por essa força? 

  
    \item Se o corpo se deslocou \Sexpr{distancia} m, qual o valor da força aplicada? 

  \end{answerlist}

\end{question}

\begin{solution}
Pelo teorema do trabalho--energia cinética, como o corpo parte do repouso,
\[
  \tau=\Delta K=\frac12 m v^2
      =\frac12\cdot\Sexpr{massa}\cdot(\Sexpr{velocidade})^2
      =\Sexpr{resp1}\,\mathrm J.
\]
Sendo a força constante e paralela ao deslocamento,
\[
  F=\frac{\tau}{d}
    =\frac{\Sexpr{resp1}}{\Sexpr{distancia}}
    =\Sexpr{resp2}\,\mathrm N.
\]

\begin{answerlist}

  \item \(\Sexpr{resp1}\,\mathrm J\)

  \item \(\Sexpr{resp2}\,\mathrm N\)

\end{answerlist}

\end{solution}

%% META-INFORMATION
%% \extype{cloze}
%% \exclozetype{num|num}
%% \exsolution{\Sexpr{resp1}|\Sexpr{resp2}}
%% \exname{Q16Trab}
%% \extol{0.1|0.1}
